<?php
/**
 * User: evaisse
 * Date: 09/12/2016
 * Time: 12:49
 */
namespace OpenApi;

/**
 * Class ArrayList
 * @package OpenApi
 */
class ArrayList extends \ArrayObject implements \JsonSerializable
{

    /**
     * @var callable
     */
    protected $validate;

    /**
     * {@inheritdoc}
     */
    public function __construct(array $input = null, callable $validator = null, $flags = 0, $iterator_class = "ArrayIterator")
    {
        parent::__construct($input ? $input : [], $flags, $iterator_class); // TODO: Change the autogenerated stub
        if ($validator) {
            $this->validate = $validator;
        }
    }

    /**
     * @param mixed $index
     * @param mixed $newval
     */
    public function offsetSet($index, $newval)
    {
        if (call_user_func($this->validate, $newval)) {
            parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
        } else {
            throw new \InvalidArgumentException('Invalid value type given');
        }
    }


    /**
     * @throws \InvalidArgumentException
     * @param int $index
     * @return boolean
     */
    public function offsetExists($index)
    {
        if (!is_int($index)) {
            throw new \InvalidArgumentException('Offset should be numeric');
        }
        return parent::offsetExists($index);
    }

    /**
     * @return array
     */
    function jsonSerialize()
    {
        return array_values($this->getArrayCopy());
    }

}